[tool.poetry]
name = "curs"
version = "0.1.0"
description = ""
authors = ["Kira <kirillbutakov02021994@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 88
target-version = ["py312"]
skip-string-normalization = false
include = "\\.pyi?$"
exclude = '''
/(
    \.git
    | \.tox
    | \.venv
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 119
known_third_party = ["django", "flask", "numpy", "pandas"]
skip = ["migrations"]

[tool.mypy]
python_version = "3.12"
strict = true
disallow_untyped_defs = true
check_untyped_defs = true
ignore_missing_imports = true
exclude = "(migrations|tests)"

[tool.flake8]
max-line-length = 88
exclude = ".git,__pycache__,build,dist,venv"
extend-ignore = ["E203", "W503"]